name: Build Arduino examples
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: arduino/compile-sketches@v1
     with:
      fqbn: 'arduino:avr:mega'
      libraries: |
        - name: Ethernet
          version: 1.1.3
